### ISSUE TITLE
Mosquitto on LXC returns "Error: Address already in use" after "sudo service mosquitto restart"

### ISSUE THREAD

**Issue by begleysm** [eclipse/mosquitto#1117]
I am running a Mosquitto install on a Debian 9 LXC container (hosted by a Proxmox server).

When I run the command "sudo service mosquitto restart" the broker is not restarted successfully.  I get the error "Error: Address already in use".

```
user@server:/etc/letsencrypt/scp/server.com$ sudo service mosquitto restart
[sudo] password for user: 
user@server:/etc/letsencrypt/scp/server.com$ sudo service mosquitto status 
* mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (exited) since Tue 2019-01-22 20:19:23 EST; 30s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 31328 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 31333 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)

Jan 22 20:19:23 server systemd[1]: Stopped LSB: mosquitto MQTT v3.1 message broker.
Jan 22 20:19:23 server systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Jan 22 20:19:23 server mosquitto[31333]: Starting network daemon:: mosquitto.
Jan 22 20:19:23 server systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
Jan 22 20:19:23 server mosquitto[31338]: mosquitto version 1.5.4 starting
Jan 22 20:19:23 server mosquitto[31338]: Config loaded from /etc/mosquitto/mosquitto.conf.
Jan 22 20:19:23 server mosquitto[31338]: Opening ipv6 listen socket on port 1883.
Jan 22 20:19:23 server mosquitto[31338]: Error: Address already in use
Jan 22 20:19:23 server mosquitto[96]: mosquitto version 1.5.4 terminating
Jan 22 20:19:23 server mosquitto[96]: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
```

However when I run "sudo service mosquitto stop" followed by "sudo service mosquitto start" things work fine.

```
user@server:/etc/letsencrypt/scp/server.com$ sudo service mosquitto stop
user@server:/etc/letsencrypt/scp/server.com$ sudo service mosquitto status
* mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: inactive (dead) since Tue 2019-01-22 20:30:57 EST; 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 31431 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 31398 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/mosquitto.service

Jan 22 20:20:22 server mosquitto[31403]: Socket error on client <unknown>, disconnecting.
Jan 22 20:20:39 server mosquitto[31403]: New connection from 1.2.3.4 on port 8883.
Jan 22 20:20:46 server mosquitto[31403]: Socket error on client brokeruser1, disconnecting.
Jan 22 20:20:46 server mosquitto[31403]: New client connected from 1.2.3.4 as brokeruser1 (c0, k3600, u'broker').
Jan 22 20:21:03 server mosquitto[31403]: Outgoing messages are being dropped for client brokeruser2.
Jan 22 20:30:57 server systemd[1]: Stopping LSB: mosquitto MQTT v3.1 message broker...
Jan 22 20:30:57 server mosquitto[31431]: Stopping network daemon:: mosquitto.
Jan 22 20:30:57 server systemd[1]: Stopped LSB: mosquitto MQTT v3.1 message broker.
Jan 22 20:30:57 server mosquitto[31403]: mosquitto version 1.5.4 terminating
Jan 22 20:30:57 server mosquitto[31403]: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
user@server:/etc/letsencrypt/scp/server.com$ sudo service mosquitto start
user@server:/etc/letsencrypt/scp/server.com$ sudo service mosquitto status
* mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated; vendor preset: enabled)
   Active: active (running) since Tue 2019-01-22 20:31:01 EST; 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 31431 ExecStop=/etc/init.d/mosquitto stop (code=exited, status=0/SUCCESS)
  Process: 31463 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/mosquitto.service
           `-31468 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf

Jan 22 20:31:01 server systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Jan 22 20:31:01 server mosquitto[31463]: Starting network daemon:: mosquitto.
Jan 22 20:31:01 server systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
Jan 22 20:31:01 server mosquitto[31468]: mosquitto version 1.5.4 starting
Jan 22 20:31:01 server mosquitto[31468]: Config loaded from /etc/mosquitto/mosquitto.conf.
Jan 22 20:31:01 server mosquitto[31468]: Opening ipv6 listen socket on port 1883.
Jan 22 20:31:01 server mosquitto[31468]: Opening ipv4 listen socket on port 1883.
Jan 22 20:31:01 server mosquitto[31468]: Opening ipv4 listen socket on port 8883.
Jan 22 20:31:01 server mosquitto[31468]: Opening ipv6 listen socket on port 8883.
```

What gives?  Is the restart command not attempting to release the port?  Is it not waiting long enough before it tries to start the server again?

**Comment by ralight** [comment]
Can you give any more details about how you installed this?

**Comment by begleysm** [comment]
I've got Proxmox 5.2-12 installed an a Dell R510 Server.

I created a Container using their tool with a Debian 9.3-1 Templed ate.

I updated/upgraded Debian.  I then installed Mosquitto from the moquitto.org repository with the following set of commands

```
    5  sudo curl -O http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
    6  sudo apt-key add mosquitto-repo.gpg.key 
    7  rm mosquitto-repo.gpg.key 
    8  sudo rm mosquitto-repo.gpg.key 
    9  cd /etc/apt/sources.list.d/
   10  sudo curl -O http://repo.mosquitto.org/debian/mosquitto-$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release).list
   11  sudo apt-get update
   12  sudo apt-get install mosquitto mosquitto-clients
```

Thanks for taking some time to look into this issue.

**Comment by momoskitto** [comment]
I have noticed a similar issue on debian. In debian, the mosquitto broker is restarted with the `start-stop-daemon`. Unfortunately, when stopping the service, it is only sending a signal to mosquitto, not waiting for it to shut down before starting it again, causing the "address already in use" error. I fixed it by adding the "--retry" option to the `start-stop-deamon --stop` call in /etc/init.d/mosquitto.

**Comment by begleysm** [comment]
Thank you @momoskitto, that makes a lot of sense.  That suggests that this really is a bug in the /etc/init.d/mosquitto file provided by Eclipse Mosquitto.

I've uploaded my /etc/init.d/mosquitto file [here](https://github.com/eclipse/mosquitto/files/2845718/mosquitto.txt) for reference.

For helping my problem.  Are saying you added a "--retry" option to the `start-stop-daemon --stop` call on line 58 or line 84 (or line 72 or line 100) of the attached file?  Because the --stop reference on line 84 is for "restart" but it already contains a "--retry 30".  The --stop on line 58 is for the "stop" command and does not contain a "--retry" but I wouldn't think it would be run when calling with "restart".  The other two line references are for reload and try-restart.

**Comment by momoskitto** [comment]
I actually didn't remember all details and my previous answer is unclear, thank you for your follow-up. So I checked again what I did:

I did change the call of the `start-stop-daemon` for the "stop" command, not "restart". In my case, the problem only occurred in combination with `systemd restart mosquitto.service`, which does not actually send a "restart" command but rather a "stop" followed by a "start". Therefore it helped to wait for mosquitto to exit after sending the "stop" command.

**Comment by begleysm** [comment]
Thank you.  Looking at my original output of `sudo service mosquitto restart` `sudo service mosquitto status` it would appear as though my call is also actually running a "stop" followed by a "start" so it is likely your fix will work for me as well.  Thank you.

In regards to fixing this bug:
This seems like something that should be addressed in the Mosquitto package.  I think that adding the "--retry" option is more of a quick work around and the correct approach would, ultimately, be to check for those closing of the sockets (although I don't currently know how to implement that).

**Comment by ralight** [comment]
`--retry` is a good fallback, thanks for pointing that out, but the better solution would be to use the systemd unit files that the debian official packaging uses. It's just a mistake that those aren't installed for the repo.mosquitto.org packages. I'll see about sorting that out.

**Comment by begleysm** [comment]
Thanks @ralight.  It would be great to see this addressed in the package since I suspect that whatever "work around" is implemented will likely be overwritten with an upgrade.

**Comment by ralight** [comment]
I'm closing this because the systemd file is in the latest packages, plus I've just now added `--retry 30` to the init file as a fallback.

**Comment by mmadoo** [comment]
I have tested the latest ubuntu package that has `--retry` option and the issue is still present.
If I do:
`service mosquitto stop ;service mosquitto start ; sleep 2;service mosquitto status`
then it is always OK (it shows `active (running)`)
but the command fails (it shows `active (exited)`)
`service mosquitto restart ; sleep 2;service mosquitto status`
