### ISSUE TITLE
Long delay for client connection when broker is built against libwebsockets 3.2.0

### ISSUE THREAD

**Issue by pbrenna** [eclipse/mosquitto#1406]
When the mosquitto broker is built against libwebsockets 3.2.0 (as the official package in arch linux is) and when websocket support is enabled through the configuration, clients trying to connect using the standard (non websocket) protocol experience a long delay (~30s) on connection, and subsequently get disconnected often. Tested with the mosquitto_pub client and others.

Interestingly, even if a client is killed before managing to connect, mosquitto logs it as having established the connection, after the long delay.

This was tested with mosquitto 1.6.3 and 1.6.4. When building against libwebsockets 3.1.0 this is not reproducible.

I am testing on Arch linux with the officially provided libwebsockets.

**Comment by ralight** [comment]
I believe this is fixed in the `fixes` branch, are you in a position to test it out? I can provide details if you need.

**Comment by pbrenna** [comment]
Thank you for your response. I have checked out the fixes branch, then  
```
make clean
make WITH_WEBSOCKETS=yes -j 8   
src/mosquitto -c mosquitto.conf
```

My mosquitto.conf:

```
listener 1883
protocol mqtt
max_inflight_messages 0

listener 9093
protocol websockets
max_inflight_messages 0
```

The same behavior is still present, clients take a long time to connect and get disconnected a few times a minute. I have also tried the develop branch out of curiosity, but it behaves the same way.
Let me know if i can provide further information.

**Comment by ralight** [comment]
I think it should be sorted now. Very annoying of libwebsockets to change its behaviour, but not unusual.

**Comment by pbrenna** [comment]
Great! The `fixes` branch now works fine with both versions of libwebsockets.

**Comment by ralight** [comment]
Thanks for confirming.
