### ISSUE TITLE
mosquitto.org main page contains scrambled text

### ISSUE THREAD

**Issue by bjanders** [eclipse/mosquitto#1451]
The text under the "Test" title on the main page of https://mosquitto.org says:

> plain MQTT, MQTT over TLS, MQTT over TLS (with client certificate, MQTT over WebSockets and MQTT over WebSockets with TLS.
platforms. 

At least there is a missing parenthesis, or probably one that shouldn't be there. There is the word "platforms." that doesn't seem to belong to anything. 
Maybe the text is supposed to read:
> plain MQTT, MQTT over TLS, MQTT over TLS with client certificate, MQTT over WebSockets and MQTT over WebSockets with TLS.

**Comment by ralight** [comment]
Thank you, you're quite right. That's now fixed in the repo and on the site.

**Comment by bjanders** [comment]
"platforms." has been removed, but I still see: " (with client certificate, MQTT over WebSockets and MQTT over WebSockets with TLS.", i.e., a parenthesis that should be removed, unless I'm seeing an old cached copy.

**Comment by ralight** [comment]
Ah yes, I missed that. It was actually a bracket missing. Thanks again.
