### ISSUE TITLE
Trying to bridge unsecured Mosquitto to secured Azure Iot Hub MQTT

### ISSUE THREAD

**Issue by InsomniumBR** [eclipse/mosquitto#953]
Hello,

I have been spending the latest hours trying to bridge mosquitto server to an Azure Iot Hub, unfortunately without success. =/
I have mosquitto server running on Ubuntu 14.04, it is not secured (TLS), I want to receive the messages there and them bridge them to a secured Azure IoT Hub.

Its important to say that I can send a message using mosquito_pub using the same parameters, but when using bridge the error is: **Connection Refused: unacceptable protocol version**

![image](https://user-images.githubusercontent.com/2073799/45057263-8be79780-b06b-11e8-9a08-e461ba81d7fc.png)

When using mosquitto_pub this is my command line:

`mosquitto_pub -d -h iothub-brw.azure-devices.net -i TH10_01 -u "iothub-brw.azure-devices.net/TH10_01/api-version=2016-11-14" -P "SharedAccessSignature sig=2wOw4UMC9M%2BFY...Qcso%3D&se=1567108851&sr=iothub-brw.azure-devices.net%2Fdevices%2FTH10_01" -m "mosquitto now goes live now 2" -t "devices/TH10_01/messages/events/STATE" -p 8883 -V mqttv311 --cafile iothub.cer --tls-version tlsv1.2`

And it works perfectly, but when trying to do the same with this bridge I got the unacceptable protocol error:

```
connection iothubbridge
log_type all
address iothub-brw.azure-devices.net:8883
local_clientid TH10_01_dev
remote_clientid TH10_01
remote_username iothub-brw.azure-devices.net/TH10_01/api-version=2016-11-14
remote_password "SharedAccessSignature sig=2wOw4UMC9M%2BFY...Qcso%3D&se=1567108851&sr=iothub-brw.azure-devices.net%2Fdevices%2FTH10_01"
bridge_cafile /etc/mosquitto/iothub.cer
cleansession true
bridge_protocol_version mqttv311
bridge_tls_version tlsv1.2
topic # out 0 devices/TH10_01/messages/events/ devices/TH10_01/messages/events/
```

Can anyone please help me on that?

**Comment by karlp** [comment]
You also need try_private =  false, notifictions false (or local only) and also attempt_unsubscribe = false.  You need these three with quite a lot of cloud providers.

**Comment by ralight** [comment]
@InsomniumBR did you have any luck with Karl's suggestion?

**Comment by InsomniumBR** [comment]
@ralight @karlp I am sorry, I couldn't try that yet. =(
I need to solve the problem that day, so, I managed to create a small console application (.net) for linux that subscribed to the local mqtt queue and relayed the data to Azure. But, by now I had cut the Iot Hub and sent the data through a CosmosDB directly.

**Comment by dejandundjerski** [comment]
@ralight @karlp i have the same issue and I've tried your suggestions but without success. In log analytics i see 401 auth errors. any ideas why auth does not succeed in bridge mode? while mosquito_pub using same parameters works nice?

**Comment by karlp** [comment]
@dejandundjerski then please share _your_ exact configs.  if you have working mosquitto_pub, then to get working bridge (in my experience) you just need the tryprivate, notifiactsion false, and attempt unsubscribe settings to be correct.  You have to be very careful with what you try and subscribe to as well, or you will get kicked off.

**Comment by karlp** [comment]
you need quotes.  your remote_password is almost definitely getting mangled.

**Comment by karlp** [comment]
(you probably want to revoke those SAS tokens now!)

**Comment by dejandundjerski** [comment]
Yep, i thought it was problem with quotes so i tried adding them, but again without any success :/
I am constantly receiving following errors in mosquitto log:

1538137946: Config loaded from /etc/mosquitto/mosquitto.conf.
1538137946: Opening ipv4 listen socket on port 1883.
1538137946: Opening ipv6 listen socket on port 1883.
1538137946: Bridge local.BlackBoxv2 doing local SUBSCRIBE on topic devices/BlackBoxv2/messages/events/#
1538137946: Connecting bridge bridge-to-iothub (GaTestIoT.azure-devices.net:8883)
1538137946: Bridge BlackBoxv2 sending CONNECT
1538137946: Received CONNACK on connection local.BlackBoxv2.
1538137946: Connection Refused: not authorised
1538137946: Socket error on client local.BlackBoxv2, disconnecting.

**Comment by mpoeckl** [comment]
Same here: mosquitto_pub and mosquitto_sub are working fine with IoT Hub, using the bridge (with the exact same config) it throws the error "not authorized". It looks like the mosquitto bridge is sending an invalid password, it somehow corrupts the provided password. Quotes on the password did not work either (single and double). Looks like this worked in older versions of mosquitto as I could find some blog post (from 2016) with the identical configuration and a working bridge.

**Comment by Digvijaysingh7** [comment]
Hello,

I've tried to bridge mosquitto server (Ubuntu 18.04.3) to Azure IOT hub with below code: -
# For debugging
log_type all

connection bridge-to-iothub
address NapinoIOTtest.azure-devices.net:8883
remote_username NapinoIOTtest.azure-devices.net/mydevice
remote_password SharedAccessSignature sr=NapinoIOTtest.azure-devices.net%2Fdevices%2Fmydevice&sig=NPQ10oIhmYKyvS69285hi%DvXGCKezN7PjLMb%&bkiots%3D&se=1198667940
remote_clientid mydevice
bridge_cafile /home/xyz/cert/root.pem

start_type automatic
cleansession true
try_private false
bridge_attempt_unsubscribe false
notifications false
notification_topic events/
# bridge_insecure false
bridge_protocol_version mqttv311
bridge_tls_version tlsv1
topic # out 0 devices/mydevice/messages/events/ devices/mydevice/messages/events/

I've also tried with one more code : -

# Bridge configuration
connection azureiot-bridge
log_type debug
address NapinoIOTtest.azure-devices.net:8883
remote_username NapinoIOTtest.azure-devices.net/mydevice/api-version=2016-11-14
remote_password SharedAccessSignature sr=NapinoIOTtest.azure-devices.net%2Fdevices%2Fmydevice&sig=NPQ10oIhmYKyvS6928%hiHDvXGCsrzN7PjLMb%2BkyoIs%3r&se=1598557940
remote_clientid mydevice
bridge_cafile /home/xyz/cert/root.pem
try_private false
cleansession true
start_type automatic
bridge_insecure false
bridge_protocol_version mqttv311
bridge_tls_version tlsv1
notifications false
notification_topic events/

topic devices/mydevice/messages/events/# out 1

When i'm using mosquitto_pub command, i'm getting below error: 

mosquitto_pub -h NapinoIOTtest.azure-devices.net -p 8883 -t devices/mydevice/mess                                                                                     ages/events/ -V mqttv311 -i mydevice -d -u NapinoIOTtest.azure-devices.net/mydevice -P "SharedAccessSignature sr=NapinoIOTtest.azure-devices.net%2Fdevices%2Fmydevice&sig=NPQ10oIhmYKyvS69285hiHDvXGCKezN7PjLMb%                                                                                     2BkioIs%3D&se=1598597840" -m "hello" --cafile /home/xyz/cert/root.pem -q 1
Client mydevice sending CONNECT
Client mydevice received CONNACK (0)
Client mydevice sending PUBLISH (d0, q1, r0, m1, 'devices/mydevice/messages/events/', ... (5 bytes))
Client mydevice received PUBACK (Mid: 1, RC:0)
Client mydevice sending DISCONNECT

Please help!

**Comment by karlp** [comment]
you're not getting any error from mosquitto_pub, and as far as I can tell, the original issue of this ticket has been resolved.  Check whether your mosquitto version is new enough, and also check whether azure still allows tlsv1 connections, but I think this ticket should be closed.

**Comment by ralight** [comment]
I'd be surprised if azure did support tlsv1. @Digvijaysingh7 if you can't get this figured out, please open a separate issue but I agree with Karl, this particular one is solved and so I'm closing it.

**Comment by Digvijaysingh7** [comment]
@ralight yes in some cases it is still supporting. @karlp  could you please share the steps to bridge Mosquitto server to Azure IOT hub.

**Comment by Digvijaysingh7** [comment]
@karlp  issue has been fixed i'm able to receive messages on IOT hub.

**Comment by asishsinha** [comment]
> Hello,
> I've tried to bridge mosquitto server (Ubuntu 18.04.3) to Azure IOT hub with below code: -
> For debugging
> log_type all
> connection bridge-to-iothub
> address NapinoIOTtest.azure-devices.net:8883
> remote_username NapinoIOTtest.azure-devices.net/mydevice
> remote_password SharedAccessSignature sr=NapinoIOTtest.azure-devices.net%2Fdevices%2Fmydevice&sig=NPQ10oIhmYKyvS69285hi%DvXGCKezN7PjLMb%&bkiots%3D&se=1198667940
> remote_clientid mydevice
> bridge_cafile /home/xyz/cert/root.pem
> start_type automatic
> cleansession true
> try_private false
> bridge_attempt_unsubscribe false
> notifications false
> notification_topic events/
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1
> topic # out 0 devices/mydevice/messages/events/ devices/mydevice/messages/events/
> I've also tried with one more code : -
> Bridge configuration
> connection azureiot-bridge
> log_type debug
> address NapinoIOTtest.azure-devices.net:8883
> remote_username NapinoIOTtest.azure-devices.net/mydevice/api-version=2016-11-14
> remote_password SharedAccessSignature sr=NapinoIOTtest.azure-devices.net%2Fdevices%2Fmydevice&sig=NPQ10oIhmYKyvS6928%hiHDvXGCsrzN7PjLMb%2BkyoIs%3r&se=1598557940
> remote_clientid mydevice
> bridge_cafile /home/xyz/cert/root.pem
> try_private false
> cleansession true
> start_type automatic
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1
> notifications false
> notification_topic events/
> topic devices/mydevice/messages/events/# out 1
> When i'm using mosquitto_pub command, i'm getting below error:
> mosquitto_pub -h NapinoIOTtest.azure-devices.net -p 8883 -t devices/mydevice/mess                                                                                     ages/events/ -V mqttv311 -i mydevice -d -u NapinoIOTtest.azure-devices.net/mydevice -P "SharedAccessSignature sr=NapinoIOTtest.azure-devices.net%2Fdevices%2Fmydevice&sig=NPQ10oIhmYKyvS69285hiHDvXGCKezN7PjLMb%                                                                                     2BkioIs%3D&se=1598597840" -m "hello" --cafile /home/xyz/cert/root.pem -q 1
> Client mydevice sending CONNECT
> Client mydevice received CONNACK (0)
> Client mydevice sending PUBLISH (d0, q1, r0, m1, 'devices/mydevice/messages/events/', ... (5 bytes))
> Client mydevice received PUBACK (Mid: 1, RC:0)
> Client mydevice sending DISCONNECT
> Please help!

Using this bridge configuration in the /etc/mosquito/mosquitto.conf  file works.
There is no need of the api-version in the **remote_username** and **bridge_tls_version** needs to be tlsv1.2 instead of tlsv1

# Bridge configuration
connection azureiot-bridge
log_type all
address [IOT hub shortname].azure-devices.net:8883
remote_username [IOT hub shortname].azure-devices.net/[device-id]
remote_password [sas-token]
remote_clientid [device-id]
bridge_cafile /home/MQTTbroker/cert1.pem
try_private false
cleansession true
start_type automatic
bridge_insecure false
bridge_protocol_version mqttv311
bridge_tls_version tlsv1.2
notifications false
notification_topic events/

topic devices/[device-id]/messages/events/# out 1

And then publishing messages with below command should work
$ mosquitto_pub -t devices/[device-id]/messages/events/ -m "hello world!"

**Comment by TestMannequin** [comment]
I am unfortunately still having problems with version 1.5.7 connecting to Azure IOT Hub. 

This is my config:

> connection iothub-bridge
> log_type all
> address sirhubalot.azure-devices.net:8883
> remote_username sirhubalot.azure-devices.net/azure_rpi
> remote_password SharedAccessSignature sr=sirhubalot.azure-devices.net&sig=keyhere
> remote_clientid azure_rpi
> bridge_cafile /home/pi/certs/digicert_baltimore.pem
> try_private false
> #bridge_attempt_unsubscribe false
> cleansession true
> start_type automatic
> bridge_insecure false
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1.2
> notifications false
> notification_topic events/
> topic zigbee2mqtt/# out 1

The logs after starting the service:

> 1569106775: mosquitto version 1.5.7 starting
> 1569106775: Config loaded from /etc/mosquitto/mosquitto.conf.
> 1569106775: Opening ipv4 listen socket on port 1883.
> 1569106775: Opening ipv6 listen socket on port 1883.
> 1569106775: Connecting bridge (step 1) iothub-bridge (sirhubalot.azure-devices.net:8883)
> 1569106775: Connecting bridge (step 2) iothub-bridge (sirhubalot.azure-devices.net:8883)
> 1569106775: Bridge azure_rpi sending CONNECT
> 1569106776: Received CONNACK on connection local.azure_rpi.
> 1569106776: Bridge local.azure_rpi sending UNSUBSCRIBE (Mid: 1, Topic: zigbee2mqtt/#)
> 1569106776: Bridge local.azure_rpi sending SUBSCRIBE (Mid: 2, Topic: #, QoS: 0)
> 1569106776: Bridge local.azure_rpi doing local SUBSCRIBE on topic zigbee2mqtt/#
> 1569106776: Sending PUBLISH to local.azure_rpi (d0, q0, r1, m0, 'zigbee2mqtt/bridge/state', ... (7 bytes))
> 1569106776: Sending PUBLISH to local.azure_rpi (d0, q0, r1, m0, 'zigbee2mqtt/bridge/config', ... (99 bytes))
> 1569106776: Received UNSUBACK from local.azure_rpi
> 1569106776: Received SUBACK from local.azure_rpi
> 1569106776: Socket error on client local.azure_rpi, disconnecting.
> 


And this is the mosquitto_pub that works:

> mosquitto_pub -d -h sirhubalot.azure-devices.net -i azure_rpi -u "sirhubalot.azure-devices.net/azure_rpi/" -P "SharedAccessSignature sr=sirhubalot.azure-devices.net&sig=keyhere" -m "test message" -t "zigbee2mqtt/test" -p 8883 -V mqttv311 --cafile /home/pi/certs/digicert_baltimore.pem --tls-version tlsv1.2

here is the output:
```
Client azure_rpi sending CONNECT
Client azure_rpi received CONNACK (0)
Client azure_rpi sending PUBLISH (d0, q0, r0, m1, 'zigbee2mqtt/test', ... (29 bytes))
Client azure_rpi sending DISCONNECT
```
Even this command although no errors are returned, the logging on the azure side has errors:


> ResourceId | OperationName | Category | Level | ResultDescription | properties_s
> -- | -- | -- | -- | -- | --
> /SUBSCRIPTIONS/IOTHUBS/SIRHUBALOT | ingress | DeviceTelemetry | Error | BadRequest | {"deviceId":"azure_rpi","protocol":"Mqtt","authType":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","maskedIpAddress":"64.92.21.XXX","messageId":"","messageSizeInBytes":"22","batchSize":"1","batching":"False","statusCode":"400"}
> /SUBSCRIPTIONS/IOTHUBS/SIRHUBALOT | deviceConnect | Connections | Information |   | {"deviceId":"azure_rpi","protocol":"Mqtt","authType":null,"maskedIpAddress":"64.92.21.XXX","statusCode":null}
> /SUBSCRIPTIONS/IOTHUBS/SIRHUBALOT | deviceDisconnect | Connections | Error | BadRequest | {"deviceId":"azure_rpi","protocol":"Mqtt","authType":null,"maskedIpAddress":"64.92.21.XXX","statusCode":"400"}
> 


I'm not sure what to try next, any ideas much appreciated.

**Comment by TestMannequin** [comment]
erm, quite embarrassing, Azure IOT hub doesn't support topic names other than:
devices/{devicename}/messages/events/

So as soon as I fixed the output topic name, it worked. Sorry!
